using System.Collections.Generic;

namespace UnifromCheat_REPO
{
    public partial class TooltipsLanguages
    {
        private static void AddExtendedTooltipPacks()
        {
            AddTooltip("enableProceduralSnowfall", "降雪を有効にします", "눈 내리기를 활성화합니다", "Włącza opady śniegu", "Activa la nevada", "Active la chute de neige", "يُفعّل تساقط الثلج", "Укључује снежне падавине", "Уключае снегапад", "Kar yağışını etkinleştirir");
            AddTooltip("ps_onlyInMenu", "メニュー内でのみ動作します", "메뉴 안에서만 작동합니다", "Działa tylko w menu", "Funciona solo en el menú", "Fonctionne uniquement dans le menu", "يعمل داخل القائمة فقط", "Ради само у менију", "Працуе толькі ў меню", "Yalnızca menüde çalışır");
            AddTooltip("ps_fallSpeed", "雪の降る速度", "눈 내리는 속도", "Prędkość opadania śniegu", "Velocidad de caída de la nieve", "Vitesse de chute de la neige", "سرعة سقوط الثلج", "Брзина падања снега", "Хуткасць падзення снегу", "Karın düşme hızı");
            AddTooltip("ps_spawnInterval", "雪片の生成間隔", "눈송이 생성 간격", "Interwał pojawiania się płatków", "Intervalo de aparición de copos", "Intervalle d'apparition des flocons", "الفاصل بين ظهور رقاقات الثلج", "Интервал стварања пахуља", "Інтэрвал з'яўлення сняжынак", "Kar tanesi oluşma aralığı");
            AddTooltip("ps_scale", "雪片のサイズ", "눈송이 크기", "Rozmiar płatków śniegu", "Tamaño de los copos", "Taille des flocons", "حجم رقاقات الثلج", "Величина пахуља", "Памер сняжынак", "Kar tanesi boyutu");
            AddTooltip("ps_dynamicScale", "サイズを動的に変更します", "눈송이 크기를 동적으로 바꿉니다", "Włącza dynamiczny rozmiar", "Activa el tamaño dinámico", "Active la taille dynamique", "يجعل الحجم ديناميكيًا", "Омогућава динамичку величину", "Робіць памер дынамічным", "Boyutu dinamik yapar");
            AddTooltip("ps_scaleRangeA", "最小サイズ", "최소 크기", "Minimalny rozmiar", "Tamaño mínimo", "Taille minimale", "الحد الأدنى للحجم", "Минимална величина", "Мінімальны памер", "En küçük boyut");
            AddTooltip("ps_scaleRangeB", "最大サイズ", "최대 크기", "Maksymalny rozmiar", "Tamaño máximo", "Taille maximale", "الحد الأقصى للحجم", "Максимална величина", "Максімальны памер", "En büyük boyut");
            AddTooltip("pss_customSource", "カスタム雪片テクスチャ", "사용자 눈송이 텍스처", "Własna tekstura płatka śniegu", "Textura personalizada del copo", "Texture personnalisée du flocon", "نسيج رقاقات ثلج مخصص", "Прилагођена текстура пахуље", "Уласная тэкстура сняжынкі", "Özel kar tanesi dokusu");
            AddTooltip("getCursorOffsetLabel", "カーソルアイコンのオフセット（更新するにはメニューを開き直してください）", "커서 아이콘 오프셋(갱신하려면 메뉴를 다시 여세요)", "Przesunięcie ikony kursora (aby odświeżyć, otwórz menu ponownie)", "Desplazamiento del icono del cursor (reabre el menú para actualizar)", "Décalage de l'icône du curseur (rouvrez le menu pour actualiser)", "إزاحة أيقونة المؤشر (أعد فتح القائمة للتحديث)", "Помак иконе курсора (поново отвори мени да се ажурира)", "Зрух значка курсора (каб абнавіць, зноў адкрый меню)", "İmleç simgesi kayması (güncellemek için menüyü yeniden aç)");
            AddTooltip("customCursorSource", "カスタムカーソルアイコン", "사용자 커서 아이콘", "Własna ikona kursora", "Icono de cursor personalizado", "Icône de curseur personnalisée", "أيقونة مؤشر مخصصة", "Прилагођена икона курсора", "Уласны значок курсора", "Özel imleç simgesi");
            AddTooltip("syncTextColorWithGlow", "テキスト色を発光効果に自動同期します", "텍스트 색상을 발광 효과와 자동으로 동기화합니다", "Automatycznie synchronizuje kolor tekstu z poświatą", "Sincroniza automáticamente el color del texto con el brillo", "Synchronise automatiquement la couleur du texte avec la lueur", "يُزامن لون النص تلقائيًا مع التوهج", "Аутоматски усклађује боју текста са сјајем", "Аўтаматычна сінхранізуе колер тэксту са свячэннем", "Metin rengini parıltıyla otomatik eşitler");
            AddTooltip("hintsColor", "固定ヒントの色を変更します", "고정 힌트의 색상을 바꿉니다", "Zmienia kolor stałych podpowiedzi", "Cambia el color de las pistas fijas", "Change la couleur des indications fixes", "يغيّر لون التلميحات الثابتة", "Мења боју сталних савета", "Змяняе колер статычных падказак", "Sabit ipuçlarının rengini değiştirir");
            AddTooltip("MenuOpacity", "メニューの透明度を調整します", "메뉴 투명도를 조정합니다", "Dostosowuje przezroczystość menu", "Ajusta la transparencia del menú", "Ajuste la transparence du menu", "يضبط شفافية القائمة", "Подешава провидност менија", "Наладжвае празрыстасць меню", "Menü saydamlığını ayarlar");
            AddTooltip("PressLabelInfo", "押す:", "누르기:", "Naciśnij:", "Pulsa:", "Appuyez :", "اضغط:", "Притисни:", "Націсніце:", "Bas:");
            AddTooltip("insertInfo", "メニューを開閉します。", "메뉴를 열거나 닫습니다.", "Otwiera lub zamyka menu.", "Abre o cierra el menú.", "Ouvre ou ferme le menu.", "يفتح القائمة أو يغلقها.", "Отвара или затвара мени.", "Адкрывае або закрывае меню.", "Menüyü açar veya kapatır.");
            AddTooltip("hideAllHints", "すべての固定ヒントを非表示にします", "모든 고정 힌트를 숨깁니다", "Ukrywa wszystkie stałe podpowiedzi", "Oculta todas las pistas fijas", "Masque toutes les indications fixes", "يخفي كل التلميحات الثابتة", "Сакрива све сталне савете", "Хавае ўсе статычныя падказкі", "Tüm sabit ipuçlarını gizler");
            AddTooltip("hideAllTooltips", "すべてのフローティングツールチップを非表示にします", "모든 떠다니는 툴팁을 숨깁니다", "Ukrywa wszystkie pływające podpowiedzi", "Oculta todos los tooltips flotantes", "Masque toutes les infobulles flottantes", "يخفي كل التلميحات العائمة", "Сакрива све плутајуће описе", "Хавае ўсе плаваючыя падказкі", "Tüm yüzen ipuçlarını gizler");
            AddTooltip("hideMe", "すべての視覚変更を無効にし、メニューをブロックします", "모든 시각 변경을 끄고 메뉴를 막습니다", "Wyłącza wszystkie zmiany wizualne i blokuje menu", "Desactiva todos los cambios visuales y bloquea el menú", "Désactive tous les changements visuels et bloque le menu", "يعطّل كل التغييرات البصرية ويمنع القائمة", "Искључује све визуелне измене и блокира мени", "Адключае ўсе візуальныя змены і блакуе меню", "Tüm görsel değişiklikleri kapatır ve menüyü kilitler");
            AddTooltip("unloadCheat", "ゲームからチートをアンロードします", "게임에서 치트를 언로드합니다", "Wyładowuje cheat z gry", "Descarga el cheat del juego", "Décharge le cheat du jeu", "يفرغ الغش من اللعبة", "Искључује cheat из игре", "Выгружае чыт з гульні", "Hileyi oyundan kaldırır");
            AddTooltip("keybindPressKeys", "キーを押してください...", "키를 누르세요...", "Naciśnij klawisze...", "Pulsa las teclas...", "Appuyez sur les touches...", "اضغط المفاتيح...", "Притисни тастере...", "Націсніце клавішы...", "Tuşlara bas...");
            AddTooltip("keybindNoInsert", "Insert キーは使用できません", "Insert 키는 사용할 수 없습니다", "Klawisz Insert jest niedozwolony", "Insert no está permitido", "La touche Insert n'est pas autorisée", "مفتاح Insert غير مسموح", "Insert није дозвољен", "Insert забаронены", "Insert kullanılamaz");
            AddTooltip("unloadConfirmTitle", "チートをアンロードしますか？", "치트를 언로드할까요?", "Wyładować cheat?", "¿Descargar el cheat?", "Décharger le cheat ?", "هل تريد إلغاء تحميل الغش؟", "Искључити cheat?", "Выгрузіць чыт?", "Hile kaldırılsın mı?");
            AddTooltip("unloadConfirmWarning", "再読み込みするまでモッドは無効になります。", "다시 불러오기 전까지 모드가 비활성화됩니다.", "To wyłączy mod, dopóki nie załadujesz go ponownie.", "Esto desactivará el mod hasta que lo cargues de nuevo.", "Cela désactivera le mod jusqu'à son prochain chargement.", "سيتم تعطيل المود حتى تعيد تحميله.", "Ово ће искључити мод док га поново не учиташ.", "Гэта адключыць мод, пакуль вы зноў яго не загрузіце.", "Bu işlem mod tekrar yüklenene kadar onu devre dışı bırakır.");
            AddTooltip("unloadConfirmDynamicWarning", "動的アンロード後に不具合が発生することがあります。", "동적 언로드 후 버그가 생길 수 있습니다.", "Dynamiczne wyładowanie może po zakończeniu powodować błędy.", "La descarga dinámica puede causar errores después de completarse.", "Le déchargement dynamique peut provoquer des bugs après son exécution.", "قد يؤدي التفريغ الديناميكي إلى أخطاء بعد اكتماله.", "Динамичко искључивање може изазвати багове после завршетка.", "Дынамічная выгрузка можа выклікаць памылкі пасля завяршэння.", "Dinamik kaldırma tamamlandıktan sonra hatalara yol açabilir.");
            AddTooltip("confirmButton", "確認", "확인", "POTWIERDŹ", "CONFIRMAR", "CONFIRMER", "تأكيد", "ПОТВРДИ", "ПАЦВЕРДЗІЦЬ", "ONAYLA");
            AddTooltip("cancelButton", "キャンセル", "취소", "ANULUJ", "CANCELAR", "ANNULER", "إلغاء", "ОТКАЖИ", "СКАСАВАЦЬ", "İPTAL");

            AddTooltip("crouchSpeedHack", "しゃがみ速度", "웅크리기 속도", "Prędkość kucania", "Velocidad agachado", "Vitesse accroupie", "سرعة القرفصة", "Брзина чучња", "Хуткасць прысяду", "Çömelme hızı");
            AddTooltip("customfov", "視野角（FOV）を変更します", "시야각(FOV)을 변경합니다", "Zmienia pole widzenia (FOV)", "Cambia tu campo de visión (FOV)", "Change votre champ de vision (FOV)", "يغيّر مجال الرؤية (FOV)", "Мења видно поље (FOV)", "Змяняе поле зроку (FOV)", "Görüş açını (FOV) değiştirir");
            AddTooltip("dragWindow", "メニューウィンドウをドラッグできるようにします", "메뉴 창을 드래그할 수 있게 합니다", "Pozwala przeciągać okno menu", "Permite arrastrar la ventana del menú", "Autorise le déplacement de la fenêtre du menu", "يسمح بسحب نافذة القائمة", "Дозвољава померање прозора менија", "Дазваляе перацягваць акно меню", "Menü penceresinin sürüklenmesine izin verir");
            AddTooltip("enemiesFreeze", "テレポート後も移動を凍結したままにします", "텔레포트 후에도 이동을 얼린 상태로 유지합니다", "Pozostawia ruch zamrożony po teleportacji", "Mantiene el movimiento congelado tras el teletransporte", "Maintient le mouvement gelé après la téléportation", "يبقي الحركة مجمدة بعد النقل", "Задржава кретање замрзнутим после телепорта", "Пакідае рух замарожаным пасля тэлепарта", "Işınlamadan sonra hareketi donmuş halde tutar");
            AddTooltip("enemiesKinematic", "テレポート中に敵の Rigidbody を kinematic にして固定します", "텔레포트 중 적의 리지드바디를 kinematic으로 고정합니다", "Zamraża rigidbody wroga (kinematic) podczas teleportacji", "Congela el rigidbody del enemigo (kinematic) durante el teletransporte", "Fige le rigidbody de l'ennemi (kinematic) pendant la téléportation", "يجمّد rigidbody العدو (kinematic) أثناء النقل", "Замрзава rigidbody непријатеља (kinematic) током телепорта", "Замарожвае rigidbody ворага (kinematic) падчас тэлепарта", "Işınlama sırasında düşman rigidbody'sini kinematic olarak sabitler");
            AddTooltip("enemiesOneAny", "ランダムな敵1体をテレポートします", "무작위 적 하나를 텔레포트합니다", "Teleportuje jednego losowego wroga", "Teletransporta un enemigo aleatorio", "Téléporte un ennemi aléatoire", "ينقل عدوًا عشوائيًا واحدًا", "Телепортује једног насумичног непријатеља", "Тэлепартуе аднаго выпадковага ворага", "Bir rastgele düşmanı ışınlar");
            AddTooltip("enemiesTp", "敵をプレイヤー、回収地点、または奈落へテレポートします", "적을 플레이어, 수집 지점 또는 공허로 순간이동합니다", "Teleportuje wrogów do gracza, punktów zbiórki lub w pustkę", "Teletransporta enemigos al jugador, a los puntos de recogida o al vacío", "Téléporte les ennemis vers le joueur, les points de collecte ou le vide", "ينقل الأعداء إلى اللاعب أو نقاط التجميع أو الفراغ", "Телепортује непријатеље до играча, тачака сакупљања или у празнину", "Тэлепартуе ворагаў да гульца, пунктаў збору або ў пустэчу", "Düşmanları oyuncuya, toplama noktalarına veya boşluğa ışınlar");
            AddTooltip("enemiesTpOnTouch", "プレイヤー接触時に敵をテレポートします", "플레이어가 닿으면 적을 텔레포트합니다", "Teleportuje wroga przy kontakcie z graczem", "Teletransporta al enemigo al tocar al jugador", "Téléporte l'ennemi au contact du joueur", "ينقل العدو عند لمس اللاعب", "Телепортује непријатеља на додир играча", "Тэлепартуе ворага пры дотыку да гульца", "Oyuncuya dokununca düşmanı ışınlar");
            AddTooltip("flashlightSettings", "懐中電灯の設定を変更します", "손전등 속성을 조정합니다", "Pozwala dostosować właściwości latarki", "Personaliza las propiedades de la linterna", "Personnalise les paramètres de la lampe torche", "يخصص خصائص المصباح اليدوي", "Прилагођава подешавања лампе", "Наладжвае ўласцівасці ліхтарыка", "El feneri özelliklerini özelleştirir");
            AddTooltip("fragilityOff", "アイテムの壊れやすさを無効にします", "아이템의 깨짐을 비활성화합니다", "Wyłącza kruchość przedmiotów", "Desactiva la fragilidad de los objetos", "Désactive la fragilité des objets", "يعطّل هشاشة العناصر", "Искључује ломљивост предмета", "Адключае крохкасць прадметаў", "Eşya kırılganlığını kapatır");
            AddTooltip("fullbright", "すべての場所を最大輝度にします", "모든 곳의 밝기를 최대로 만듭니다", "Wymusza maksymalną jasność wszędzie", "Fuerza el brillo máximo en todas partes", "Force la luminosité maximale partout", "يفرض أقصى سطوع في كل مكان", "Приморава максималну осветљеност свуда", "Прымушае максімальную яркасць усюды", "Her yerde en yüksek parlaklığı zorlar");
            AddTooltip("freecam", "観戦中に自由カメラを使用します", "관전 중 자유 카메라 모드를 사용합니다", "Tryb swobodnej kamery podczas obserwacji", "Modo de cámara libre mientras observas", "Mode caméra libre pendant le spectateur", "وضع الكاميرا الحرة أثناء المشاهدة", "Слободна камера током посматрања", "Рэжым свабоднай камеры падчас назірання", "İzlerken serbest kamera modunu açar");
            AddTooltip("diedCockroach", "死亡後の頭を使用中でも移動できます", "죽은 머리를 사용하는 동안에도 이동할 수 있습니다", "Pozwala poruszać się podczas używania głowy po śmierci", "Permite moverse mientras usas tu cabeza tras morir", "Permet de bouger en utilisant votre tête après la mort", "يسمح بالحركة أثناء استخدام رأسك بعد الموت", "Омогућава кретање док користиш своју главу после смрти", "Дазваляе рухацца, калі выкарыстоўваеш сваю галаву пасля смерці", "Ölümden sonraki kafanı kullanırken hareket etmeyi sağlar");
            AddTooltip("diedCockroachForce", "死亡後の頭の移動力", "죽은 머리 이동 힘", "Siła ruchu głowy po śmierci", "Fuerza de movimiento de la cabeza muerta", "Force de déplacement de la tête après la mort", "قوة حركة الرأس بعد الموت", "Снага кретања главе после смрти", "Сіла руху галавы пасля смерці", "Ölü kafa hareket gücü");
            AddTooltip("ghostItems", "アイテムが壁を通り抜けます", "아이템이 벽을 통과할 수 있습니다", "Przedmioty mogą przenikać przez ściany", "Los objetos pueden atravesar paredes", "Les objets peuvent traverser les murs", "يمكن للعناصر المرور عبر الجدران", "Предмети могу да пролазе кроз зидове", "Прадметы могуць праходзіць праз сцены", "Eşyalar duvarların içinden geçebilir");
            AddTooltip("godMode", "プレイヤーを不死にします", "플레이어를 무적으로 만듭니다", "Gracz staje się nieśmiertelny", "Hace inmortal al jugador", "Rend le joueur immortel", "يجعل اللاعب خالدًا", "Чини играча бесмртним", "Робіць гульца несмяротным", "Oyuncuyu ölümsüz yapar");
            AddTooltip("hideHints", "画面上のヒントをすべて非表示にします（読んでいるものを除く）", "화면의 힌트를 모두 숨깁니다(현재 읽는 항목 제외)", "Ukrywa wszystkie podpowiedzi na ekranie (oprócz tej, którą czytasz)", "Oculta todas las pistas en pantalla (excepto la que estás leyendo)", "Masque toutes les indications à l'écran (sauf celle en cours de lecture)", "يخفي كل تلميحات الشاشة (عدا التي تقرؤها الآن)", "Сакрива све савете на екрану (осим оног који читаш)", "Хавае ўсе падказкі на экране (акрамя той, якую вы зараз чытаеце)", "Ekrandaki tüm ipuçlarını gizler (okuduğun hariç)");
            AddTooltip("infSprint", "プレイヤーのスタミナを無限にします", "플레이어에게 무한한 스태미나를 줍니다", "Daje graczowi nieskończoną wytrzymałość", "Da al jugador resistencia infinita", "Donne au joueur une endurance infinie", "يمنح اللاعب قدرة تحمل غير محدودة", "Даје играчу бесконачну издржљивост", "Дае гульцу бясконцую вынослівасць", "Oyuncuya sınırsız dayanıklılık verir");
            AddTooltip("infHeadEnergy", "頭越しの会話にエネルギーが不要になります", "머리로 말할 때 에너지가 필요하지 않습니다", "Mówienie przez głowę nie wymaga energii", "Hablar con la cabeza no requiere energía", "Parler via la tête ne consomme pas d'énergie", "الكلام عبر الرأس لا يحتاج إلى طاقة", "Разговор преко главе не троши енергију", "Размова праз галаву не патрабуе энергіі", "Kafa üzerinden konuşmak enerji gerektirmez");
            AddTooltip("infAmmo", "エネルギー武器のバッテリー消費を防ぎます", "에너지 무기가 배터리를 소모하지 않게 합니다", "Zapobiega zużywaniu baterii przez broń energetyczną", "Evita que las armas de energía gasten batería", "Empêche les armes à énergie de consommer la batterie", "يمنع أسلحة الطاقة من استهلاك البطارية", "Спречава енергетско оружје да троши батерију", "Не дае энергетычнай зброі траціць зарад", "Enerji silahlarının batarya harcamasını önler");
            AddTooltip("jumpForce", "ジャンプ力を調整します", "점프 힘을 조정합니다", "Dostosowuje siłę skoku", "Ajusta la fuerza del salto", "Ajuste la force du saut", "يضبط قوة القفز", "Подешава снагу скока", "Наладжвае сілу скачка", "Zıplama gücünü ayarlar");
            AddTooltip("liteItems", "アイテムを軽量化します（最小重量）", "아이템을 매우 가볍게 만듭니다(최소 무게)", "Przedmioty stają się lekkie (minimalna waga)", "Los objetos se vuelven ligeros (peso mínimo)", "Les objets deviennent légers (poids minimal)", "يجعل العناصر خفيفة جدًا (أقل وزن)", "Предмети постају лагани (минимална тежина)", "Прадметы становяцца лёгкімі (мінімальная вага)", "Eşyaları hafif yapar (en düşük ağırlık)");
            AddTooltip("multiJumps", "空中で複数回ジャンプできます", "공중에서 여러 번 점프할 수 있습니다", "Pozwala na wielokrotne skoki w powietrzu", "Permite varios saltos en el aire", "Permet plusieurs sauts en l'air", "يسمح بعدة قفزات في الهواء", "Омогућава више скокова у ваздуху", "Дазваляе некалькі скачкоў у паветры", "Havada birden fazla zıplamaya izin verir");
            AddTooltip("noTokenHud", "コスメボックスのトークン HUD を非表示にします", "코스메틱 박스의 토큰 HUD를 숨깁니다", "Ukrywa HUD żetonów kosmetycznych z pudełek kosmetycznych", "Oculta el HUD de tokens cosméticos de las cajas cosméticas", "Masque le HUD des jetons cosmétiques des coffres cosmétiques", "يخفي واجهة رموز الزينة من صناديق الزينة", "Сакрива Token HUD из козметичких кутија", "Хавае HUD касметычных токенаў з касметычных скрынак", "Kozmetik kutularındaki kozmetik jeton HUD'unu gizler");
            AddTooltip("deadVoice", "死亡したプレイヤーのチャットを聞けるようになり、観戦者のように死亡プレイヤーのアイコンが表示されます", "죽은 플레이어의 채팅을 들을 수 있고 관전자처럼 죽은 플레이어 아이콘이 표시됩니다", "Słyszysz czat martwych graczy i widzisz ich ikony jak obserwator", "Oyes el chat de los jugadores muertos y ves sus iconos como espectador", "Vous entendez le chat des joueurs morts et voyez leurs icônes comme un spectateur", "تسمع دردشة اللاعبين الموتى وترى أيقوناتهم مثل المشاهد", "Чујеш чет мртвих играча и видиш њихове иконе као посматрач", "Вы чуеце чат мёртвых гульцоў і бачыце іх значкі як назіральнік", "Ölü oyuncuların sohbetini duyarsın ve izleyici gibi ölü oyuncu simgelerini görürsün");
            AddTooltip("noclip", "壁をすり抜けて移動します", "벽을 통과해 날아다닙니다", "Pozwala latać przez ściany", "Permite volar a través de las paredes", "Permet de traverser les murs en volant", "يتيح الطيران عبر الجدران", "Омогућава летење кроз зидове", "Дазваляе лётаць праз сцены", "Duvarların içinden uçmanı sağlar");
            AddTooltip("noclipSpeed", "Noclip 中の移動速度", "노클립 사용 중 이동 속도", "Prędkość podczas aktywnego noclipu", "Velocidad mientras noclip está activo", "Vitesse lorsque le noclip est actif", "السرعة أثناء تفعيل noclip", "Брзина док је noclip активан", "Хуткасць пры актыўным noclip", "Noclip etkinken hareket hızı");
            AddTooltip("noPostProcessing", "画面の視覚的な歪みを無効にします", "화면 왜곡 같은 후처리 효과를 끕니다", "Wyłącza wizualne zniekształcenia obrazu", "Desactiva las distorsiones visuales de la imagen", "Désactive les distorsions visuelles de l'image", "يعطّل تشوهات الصورة البصرية", "Искључује визуелна изобличења слике", "Адключае візуальныя скажэнні выявы", "Görüntüdeki görsel bozulmaları kapatır");
            AddTooltip("tumbleBypass", "Tumble Climb と完全しゃがみからの立ち上がり制限を一部解除します", "Tumble Climb와 완전 숙이기 상태의 기상 제한을 일부 해제합니다", "Częściowo usuwa blokady tumble climb i wstawania z pełnego kucania", "Elimina parcialmente los bloqueos de tumble climb y de levantarse desde la sentadilla total", "Supprime partiellement les blocages de tumble climb et de relevé depuis l'accroupissement complet", "يزيل جزئيًا قيود tumble climb والنهوض من القرفصة الكاملة", "Делимично уклања закључавање tumble climb и устајања из пуног чучња", "Часткова прыбірае блакіроўкі tumble climb і ўставання з поўнага прыседу", "Tumble climb ve tam çömelmeden ayağa kalkma kilitlerini kısmen kaldırır");
            AddTooltip("noTumbleCooldown", "tumble 終了後のクールダウンを削除します", "텀블 종료 후 대기시간을 제거합니다", "Usuwa czas odnowienia po wyjściu z tumble", "Elimina el enfriamiento al salir de tumble", "Supprime le délai après la sortie de tumble", "يزيل مهلة الخروج من tumble", "Уклања хлађење после изласка из tumble", "Прыбірае затрымку пасля выхаду з tumble", "Tumble çıkış bekleme süresini kaldırır");
            AddTooltip("oneShotKill", "敵を一撃で倒します", "적을 한 번에 처치합니다", "Zabija wrogów jednym uderzeniem", "Mata a los enemigos de un golpe", "Tue les ennemis en un coup", "يقتل الأعداء بضربة واحدة", "Убија непријатеље једним ударцем", "Забівае ворагаў адным ударам", "Düşmanları tek vuruşta öldürür");
            AddTooltip("peacefulEnemies", "敵があなたを無視します。", "적들이 당신을 무시합니다.", "Wrogowie ignorują gracza.", "Los enemigos te ignoran.", "Les ennemis vous ignorent.", "الأعداء يتجاهلونك.", "Непријатељи те игноришу.", "Ворагі ігнаруюць вас.", "Düşmanlar seni görmezden gelir.");
            AddTooltip("protectedSession", "負けた後のセーブ削除を防ぎます（敗者アリーナで死ぬ前に退出した場合）", "패배 후 저장 삭제를 막습니다(패자 경기장에서 죽기 전에 나가면)", "Zapobiega usunięciu zapisu po przegranej (jeśli wyjdziesz przed śmiercią na arenie przegranych)", "Evita que se borre la partida al perder (si sales antes de morir en la arena de perdedores)", "Empêche la suppression de la sauvegarde après une défaite (si vous quittez avant de mourir dans l'arène des perdants)", "يمنع حذف الحفظ بعد الخسارة (إذا خرجت قبل الموت في ساحة الخاسرين)", "Спречава брисање сачуване игре после пораза (ако изађеш пре смрти у арени губитника)", "Прадухіляе выдаленне захавання пасля паразы (калі выйсці да смерці на арэне тых, хто прайграў)", "Kaybettikten sonra kaydın silinmesini önler (kaybedenler arenasında ölmeden önce çıkarsan)");
            AddTooltip("renderDistance", "ゲームの描画距離", "게임 렌더 거리", "Zasięg renderowania gry", "Distancia de renderizado del juego", "Distance de rendu du jeu", "مسافة الرسم في اللعبة", "Дистанца исцртавања игре", "Дыстанцыя рэндару гульні", "Oyunun render mesafesi");
            AddTooltip("rgbPlayer", "プレイヤーの色を自動で切り替えます", "플레이어 색상을 자동으로 순환합니다", "Automatycznie zmienia kolor gracza", "Cambia automáticamente el color del jugador", "Fait automatiquement défiler la couleur du joueur", "يغيّر لون اللاعب تلقائيًا", "Аутоматски мења боју играча", "Аўтаматычна змяняе колер гульца", "Oyuncu rengini otomatik olarak döndürür");
            AddTooltip("rgbPlayerUpdateInterval", "色の更新間隔（ms）", "색상 갱신 간격(ms)", "Interwał aktualizacji koloru (ms)", "Intervalo de actualización del color (ms)", "Intervalle de mise à jour de la couleur (ms)", "الفاصل بين تحديثات اللون (مللي ثانية)", "Интервал ажурирања боје (ms)", "Інтэрвал абнаўлення колеру (мс)", "Renk güncelleme aralığı (ms)");

            AddTooltip("showDeadHeadsWH", "死亡したプレイヤーの頭を強調表示します", "죽은 플레이어 머리를 강조 표시합니다", "Podświetla głowy martwych graczy", "Resalta las cabezas de jugadores muertos", "Met en surbrillance les têtes des joueurs morts", "يبرز رؤوس اللاعبين الموتى", "Истиче главе мртвих играча", "Падсвечвае галовы мёртвых гульцоў", "Ölü oyuncu kafalarını vurgular");
            AddTooltip("showEnemiesWH", "敵を強調表示します", "적을 강조 표시합니다", "Podświetla wrogów", "Resalta a los enemigos", "Met en surbrillance les ennemis", "يبرز الأعداء", "Истиче непријатеље", "Падсвечвае ворагаў", "Düşmanları vurgular");
            AddTooltip("showEnemyHealthWH", "敵の体力を表示します", "적 체력을 표시합니다", "Pokazuje zdrowie wroga", "Muestra la salud del enemigo", "Affiche la santé de l'ennemi", "يعرض صحة العدو", "Приказује здравље непријатеља", "Паказвае здароўе ворага", "Düşman canını gösterir");
            AddTooltip("showEnemyNameWH", "敵の名前を表示します", "적 이름을 표시합니다", "Pokazuje nazwę wroga", "Muestra el nombre del enemigo", "Affiche le nom de l'ennemi", "يعرض اسم العدو", "Приказује име непријатеља", "Паказвае імя ворага", "Düşman adını gösterir");
            AddTooltip("showEnemyGlowWH", "敵の発光を有効にします", "적 광선을 활성화합니다", "Włącza poświatę wroga", "Activa el brillo del enemigo", "Active la lueur de l'ennemi", "يفعّل توهج العدو", "Укључује сјај непријатеља", "Уключае свячэнне ворага", "Düşman parıltısını açar");
            AddTooltip("showExPointsWH", "回収地点を強調表示します", "수집 지점을 강조 표시합니다", "Podświetla punkty zbiórki", "Resalta los puntos de recogida", "Met en surbrillance les points de collecte", "يبرز نقاط التجميع", "Истиче тачке сакупљања", "Падсвечвае пункты збору", "Toplama noktalarını vurgular");
            AddTooltip("showItemNameWH", "アイテム名を表示します", "아이템 이름을 표시합니다", "Pokazuje nazwę przedmiotu", "Muestra el nombre del objeto", "Affiche le nom de l'objet", "يعرض اسم العنصر", "Приказује име предмета", "Паказвае назву прадмета", "Eşya adını gösterir");
            AddTooltip("showItemPriceWH", "アイテムの価格を表示します", "아이템 가격을 표시합니다", "Pokazuje cenę przedmiotu", "Muestra el precio del objeto", "Affiche le prix de l'objet", "يعرض سعر العنصر", "Приказује цену предмета", "Паказвае кошт прадмета", "Eşya fiyatını gösterir");
            AddTooltip("showItemsWH", "貴重品を強調表示します", "귀중품을 강조 표시합니다", "Podświetla kosztowności", "Resalta los objetos valiosos", "Met en surbrillance les objets de valeur", "يبرز الأشياء الثمينة", "Истиче вредне предмете", "Падсвечвае каштоўнасці", "Değerli eşyaları vurgular");
            AddTooltip("showCosmeticBoxesWH", "コスメボックスを強調表示します", "코스메틱 박스를 강조 표시합니다", "Podświetla skrzynki kosmetyczne", "Resalta las cajas cosméticas", "Met en surbrillance les coffres cosmétiques", "يبرز صناديق الزينة", "Истиче козметичке кутије", "Падсвечвае касметычныя скрынакі", "Kozmetik kutularını vurgular");
            AddTooltip("cosmeticBoxGlowColor", "コスメボックスの発光色", "코스메틱 박스 발광 색상", "Kolor poświaty skrzynki kosmetycznej", "Color del brillo de la caja cosmética", "Couleur de lueur du coffre cosmétique", "لون توهج صندوق الزينة", "Боја сјаја козметичке кутије", "Колер свячэння касметычнай скрыначкі", "Kozmetik kutusu parıltı rengi");
            AddTooltip("cosmeticBoxTextColor", "コスメボックスの文字色", "코스메틱 박스 텍스트 색상", "Kolor tekstu skrzynki kosmetycznej", "Color del texto de la caja cosmética", "Couleur du texte du coffre cosmétique", "لون نص صندوق الزينة", "Боја текста козметичке кутије", "Колер тэксту касметычнай скрыначкі", "Kozmetik kutusu metin rengi");
            AddTooltip("showCosmeticBoxRarity", "コスメボックス名の下にレア度を表示します", "코스메틱 박스 이름 아래에 희귀도를 표시합니다", "Pokazuje rzadkość skrzynki kosmetycznej pod etykietą", "Muestra la rareza de la caja cosmética debajo de la etiqueta", "Affiche la rareté du coffre cosmétique sous le libellé", "يعرض ندرة صندوق الزينة تحت الاسم", "Приказује реткост козметичке кутије испод назива", "Паказвае рэдкасць касметычнай скрыначкі пад назвай", "Kozmetik kutusunun nadirliğini etiketin altında gösterir");
            AddTooltip("cosmeticBoxTextAlpha", "コスメボックスの文字透明度", "코스메틱 박스 텍스트 투명도", "Przezroczystość tekstu skrzynki kosmetycznej", "Transparencia del texto de la caja cosmética", "Transparence du texte du coffre cosmétique", "شفافية نص صندوق الزينة", "Провидност текста козметичке кутије", "Празрыстасць тэксту касметычнай скрыначкі", "Kozmetik kutusu metin saydamlığı");
            AddTooltip("cosmeticBoxTextSize", "コスメボックスの文字サイズ", "코스메틱 박스 텍스트 크기", "Rozmiar tekstu skrzynki kosmetycznej", "Tamaño del texto de la caja cosmética", "Taille du texte du coffre cosmétique", "حجم نص صندوق الزينة", "Величина текста козметичке кутије", "Памер тэксту касметычнай скрыначкі", "Kozmetik kutusu metin boyutu");
            AddTooltip("showMoneyBagsWH", "金袋を強調表示します", "돈 가방을 강조 표시합니다", "Podświetla worki z pieniędzmi", "Resalta las bolsas de dinero", "Met en surbrillance les sacs d'argent", "يبرز أكياس المال", "Истиче вреће с новцем", "Падсвечвае мяшкі з грашыма", "Para çantalarını vurgular");
            AddTooltip("showPlayerGlowWH", "プレイヤーの発光を有効にします", "플레이어 발광을 활성화합니다", "Włącza poświatę gracza", "Activa el brillo del jugador", "Active la lueur du joueur", "يفعّل توهج اللاعب", "Укључује сјај играча", "Уключае свячэнне гульца", "Oyuncu parıltısını açar");
            AddTooltip("showPlayerHealthWH", "プレイヤーの体力を表示します", "플레이어 체력을 표시합니다", "Pokazuje zdrowie gracza", "Muestra la salud del jugador", "Affiche la santé du joueur", "يعرض صحة اللاعب", "Приказује здравље играча", "Паказвае здароўе гульца", "Oyuncu canını gösterir");
            AddTooltip("showPlayerNameWH", "プレイヤー名を表示します", "플레이어 이름을 표시합니다", "Pokazuje nazwę gracza", "Muestra el nombre del jugador", "Affiche le nom du joueur", "يعرض اسم اللاعب", "Приказује име играча", "Паказвае імя гульца", "Oyuncu adını gösterir");
            AddTooltip("showPlayersWH", "プレイヤーを強調表示します", "플레이어를 강조 표시합니다", "Podświetla graczy", "Resalta a los jugadores", "Met en surbrillance les joueurs", "يبرز اللاعبين", "Истиче играче", "Падсвечвае гульцоў", "Oyuncuları vurgular");
            AddTooltip("sortByPriceWH", "貴重品を価格帯で並び替えます", "귀중품을 가격 범위로 정렬합니다", "Sortuje kosztowności według przedziału cenowego", "Ordena los objetos valiosos por rango de precio", "Trie les objets de valeur par plage de prix", "يفرز الأشياء الثمينة حسب نطاق السعر", "Сортира вредне предмете по распону цене", "Сартуе каштоўнасці па дыяпазоне кошту", "Değerli eşyaları fiyat aralığına göre sıralar");
            AddTooltip("speedHack", "プレイヤーの移動速度を調整します", "플레이어 이동 속도를 조정합니다", "Dostosowuje prędkość ruchu gracza", "Ajusta la velocidad de movimiento del jugador", "Ajuste la vitesse de déplacement du joueur", "يضبط سرعة حركة اللاعب", "Подешава брзину кретања играча", "Наладжвае хуткасць руху гульца", "Oyuncu hareket hızını ayarlar");
            AddTooltip("sprintSpeedHack", "ダッシュ速度", "질주 속도", "Prędkość sprintu", "Velocidad de sprint", "Vitesse de sprint", "سرعة الركض", "Брзина спринта", "Хуткасць спрынту", "Koşu hızı");
            AddTooltip("valuablesDisableTouch", "接触時に固定を解除します（kinematic 時）", "접촉 시 고정을 해제합니다(kinematic일 때)", "Wyłącza zamrożenie przy dotyku (gdy kinematic)", "Descongela al tocar (cuando está en kinematic)", "Retire le gel au contact (quand kinematic est actif)", "يلغي التجميد عند اللمس (عند تفعيل kinematic)", "Укида замрзавање на додир (кад је kinematic)", "Здымае замарозку пры дотыку (калі ўключаны kinematic)", "Dokununca sabitlemeyi kaldırır (kinematic iken)");
            AddTooltip("valuablesFreeze", "テレポート後も kinematic を維持します", "텔레포트 후에도 kinematic 상태를 유지합니다", "Utrzymuje kinematic po teleportacji", "Mantiene el modo kinematic tras el teletransporte", "Conserve le mode kinematic après la téléportation", "يبقي حالة kinematic بعد النقل", "Задржава kinematic после телепорта", "Захоўвае kinematic пасля тэлепарта", "Işınlamadan sonra kinematic durumunu korur");
            AddTooltip("valuablesKinematic", "テレポート中に Rigidbody を kinematic にして固定します", "텔레포트 중에 리지드바디를 kinematic으로 고정합니다", "Zamraża rigidbody (kinematic) podczas teleportacji", "Congela los rigidbody (kinematic) durante el teletransporte", "Fige les rigidbodies (kinematic) pendant la téléportation", "يجمّد الأجسام الصلبة (kinematic) أثناء النقل", "Замрзава rigidbody (kinematic) током телепорта", "Замарожвае rigidbody (kinematic) падчас тэлепарта", "Işınlama sırasında rigidbody'leri kinematic olarak sabitler");
            AddTooltip("valuablesOneAny", "ランダムなアイテム1個をテレポートします", "무작위 아이템 하나를 텔레포트합니다", "Teleportuje jeden losowy przedmiot", "Teletransporta un objeto aleatorio", "Téléporte un objet aléatoire", "ينقل عنصرًا عشوائيًا واحدًا", "Телепортује један насумичан предмет", "Тэлепартуе адзін выпадковы прадмет", "Bir rastgele eşyayı ışınlar");
            AddTooltip("valuablesTp", "貴重品をプレイヤー、回収地点、またはカートへテレポートします", "귀중품을 플레이어, 수집 지점 또는 카트로 텔레포트합니다", "Teleportuje kosztowności do gracza, punktu zbiórki lub wózka", "Teletransporta objetos valiosos al jugador, al punto de recogida o al carrito", "Téléporte les objets de valeur vers le joueur, le point de collecte ou le chariot", "ينقل الأشياء الثمينة إلى اللاعب أو نقطة التجميع أو العربة", "Телепортује вредне предмете до играча, тачке сакупљања или колица", "Тэлепартуе каштоўнасці да гульца, пункта збору або вазка", "Değerli eşyaları oyuncuya, toplama noktasına veya arabaya ışınlar");
            AddTooltip("valuablesTpOnTouch", "接触時にアイテムをテレポートします", "접촉 시 아이템을 텔레포트합니다", "Teleportuje przedmiot przy dotyku", "Teletransporta el objeto al tocarlo", "Téléporte l'objet au contact", "ينقل العنصر عند اللمس", "Телепортује предмет на додир", "Тэлепартуе прадмет пры дотыку", "Dokununca eşyayı ışınlar");
            AddTooltip("walkSpeedHack", "歩行速度", "걷기 속도", "Prędkość chodzenia", "Velocidad al caminar", "Vitesse de marche", "سرعة المشي", "Брзина хода", "Хуткасць хады", "Yürüme hızı");

            AddTooltip("objectSpawnerItemsTab", "ゲームのアイテム一覧にあるアイテムです。", "게임 아이템 목록의 아이템입니다.", "Przedmioty z listy gry.", "Objetos de la lista del juego.", "Objets de la liste du jeu.", "عناصر من قائمة اللعبة.", "Предмети са листе игре.", "Прадметы са спісу гульні.", "Oyunun eşya listesindeki eşyalar.");
            AddTooltip("objectSpawnerValuablesTab", "貴重品とコスメボックスです。", "귀중품과 코스메틱 박스입니다.", "Kosztowności i skrzynki kosmetyczne.", "Objetos valiosos y cajas cosméticas.", "Objets de valeur et coffres cosmétiques.", "الأشياء الثمينة وصناديق الزينة.", "Вредни предмети и козметичке кутије.", "Каштоўнасці і касметычныя скрынакі.", "Değerli eşyalar ve kozmetik kutuları.");
            AddTooltip("objectSpawnerEntityTab", "敵を生成します。", "적을 생성합니다.", "Pozwala tworzyć wrogów.", "Genera enemigos.", "Permet de générer des ennemis.", "يولد الأعداء.", "Омогућава стварање непријатеља.", "Дазваляе ствараць ворагаў.", "Düşman oluşturur.");
            AddTooltip("gameControllerPlayersTab", "セッション内のプレイヤー操作です。", "세션 안의 플레이어 조작입니다.", "Akcje dla graczy w sesji.", "Acciones para los jugadores de la sesión.", "Actions pour les joueurs de la session.", "إجراءات تخص لاعبي الجلسة.", "Акције за играче у сесији.", "Дзеянні для гульцоў у сесіі.", "Oturumdaki oyuncular için işlemler.");
            AddTooltip("gameControllerMapsTab", "確認付きで現在のマップを変更します。", "확인 후 현재 맵을 변경합니다.", "Zmienia obecną mapę po potwierdzeniu.", "Cambia el mapa actual con confirmación.", "Change la carte actuelle avec confirmation.", "يغيّر الخريطة الحالية بعد التأكيد.", "Мења тренутну мапу уз потврду.", "Змяняе бягучую карту з пацвярджэннем.", "Geçerli haritayı onayla değiştirir.");
            AddTooltip("gameControllerGameplayTab", "ゲームプレイの変更です。", "게임플레이 변경입니다.", "Zmiany rozgrywki.", "Cambios en la jugabilidad.", "Changements de gameplay.", "تغييرات أسلوب اللعب.", "Измене играња.", "Змены геймплэю.", "Oynanış değişiklikleri.");
            AddTooltip("gameControllerDisableSpawnAIToggle", "新しい敵の出現を止め、現在の敵も削除します。", "새 적 생성을 막고 현재 적도 제거합니다.", "Zatrzymuje pojawianie się nowych wrogów i usuwa obecnych.", "Detiene la aparición de nuevos enemigos y elimina a los actuales.", "Empêche l'apparition de nouveaux ennemis et retire ceux déjà présents.", "يوقف ظهور الأعداء الجدد ويزيل الأعداء الحاليين.", "Зауставља појављивање нових непријатеља и уклања постојеће.", "Спыняе з'яўленне новых ворагаў і прыбірае бягучых.", "Yeni düşman oluşumunu durdurur ve mevcut düşmanları kaldırır.");
            AddTooltip("gameControllerDisableAutoExtractToggle", "ノルマ到達時の自動回収を無効にします。", "할당량 달성 시 자동 추출을 끕니다.", "Wyłącza automatyczną ekstrakcję po osiągnięciu kwoty.", "Desactiva la extracción automática al alcanzar la cuota.", "Désactive l'extraction automatique quand le quota est atteint.", "يعطّل الاستخراج التلقائي عند الوصول إلى الحصة.", "Искључује аутоматску екстракцију када се достигне квота.", "Адключае аўтаматычны збор пасля дасягнення квоты.", "Kota dolunca otomatik çıkarmayı kapatır.");
            AddTooltip("gameControllerSharedUpgradesToggle", "アップグレード箱の効果を全プレイヤーに適用します。", "업그레이드 박스 효과를 모든 플레이어에게 적용합니다.", "Ulepszenia z pudełek trafiają do wszystkich graczy.", "Las cajas de mejora aplican su efecto a todos los jugadores.", "Les boîtes d'amélioration appliquent leur effet à tous les joueurs.", "تُطبّق صناديق التطوير ترقيتها على جميع اللاعبين.", "Надоградње из кутија важе за све играче.", "Паляпшэнні з каробак прымяняюцца да ўсіх гульцоў.", "Yükseltme kutuları etkisini tüm oyunculara uygular.");
            AddTooltip("gameControllerAutoReviveToggle", "死亡後に自動で復活させます。", "죽은 뒤 자동으로 부활시킵니다.", "Automatycznie wskrzesza po śmierci.", "Reanima automáticamente tras la muerte.", "Réanime automatiquement après la mort.", "يُحيي تلقائيًا بعد الموت.", "Аутоматски оживљава после смрти.", "Аўтаматычна ажыўляе пасля смерці.", "Ölümden sonra otomatik olarak diriltir.");
            AddTooltip("gameControllerSetLevel", "指定したレベルを設定します。", "지정한 레벨을 설정합니다.", "Ustawia wskazany poziom.", "Establece el nivel indicado.", "Définit le niveau choisi.", "يضبط المستوى الذي تحدده.", "Поставља ниво који наведеш.", "Усталёўвае пазначаны ўзровень.", "Belirttiğin seviyeyi ayarlar.");
            AddTooltip("gameControllerSetMoney", "現在のセッションの所持金を設定または追加します。", "현재 세션의 돈을 설정하거나 추가합니다.", "Ustawia albo dodaje pieniądze w bieżącej sesji.", "Establece o añade dinero en la sesión actual.", "Définit ou ajoute de l'argent pour la session en cours.", "يضبط أو يضيف المال للجلسة الحالية.", "Поставља или додаје новац за тренутну сесију.", "Усталёўвае або дадае грошы для бягучай сесіі.", "Geçerli oturumun parasını ayarlar veya artırır.");
        }

        private static void AddTooltip(string key, string ja, string ko, string pl, string es, string fr, string ar, string sr, string be, string tr)
        {
            AddTooltipValue(4, key, ja);
            AddTooltipValue(5, key, ko);
            AddTooltipValue(6, key, pl);
            AddTooltipValue(7, key, es);
            AddTooltipValue(8, key, fr);
            AddTooltipValue(9, key, ar);
            AddTooltipValue(10, key, sr);
            AddTooltipValue(11, key, be);
            AddTooltipValue(12, key, tr);
        }

        private static void AddTooltipValue(int language, string key, string value)
        {
            if (!packs.TryGetValue(language, out var pack))
            {
                pack = new Dictionary<string, string>();
                packs[language] = pack;
            }

            pack[key] = value;
        }
    }
}
