using System.Collections.Generic;

namespace UnifromCheat_REPO
{
    public class TooltipsLanguages
    {
        private static readonly Dictionary<int, Dictionary<string, string>> packs =
            new Dictionary<int, Dictionary<string, string>>()
            {
                {
                    0, new Dictionary<string, string>() // English
                    {
                        { "hintsColor", "Changes the color of static hints" },
                        { "MenuOpacity", "Adjusts the menu transparency" },
                        { "PressLabelInfo", "Press:" },
                        { "insertInfo", "Open or close the menu." },
                        { "hideAllHints", "Hides all static hints" },
                        { "hideAllTooltips", "Hides all floating tooltips" },
                        { "crouchSpeedHack", "Crouch speed" },
                        { "customfov", "Changes your field of view (FOV)" },
                        { "dragWindow", "Allow dragging the menu window" },
                        { "enemiesFreeze", "Keep movement frozen after teleport" },
                        { "enemiesKinematic", "Freeze enemy rigidbody (kinematic) during teleport" },
                        { "enemiesOneAny", "Teleport one random enemy" },
                        { "enemiesTp", "Teleport enemies to player, collection points, or void" },
                        { "enemiesTpOnTouch", "Teleport enemy on player touch" },
                        { "flashlightSettings", "Customize flashlight properties" },
                        { "fragilityOff", "Disable item fragility" },
                        { "fullbright", "Forces maximum brightness everywhere" },
                        { "ghostItems", "Items can pass through walls" },
                        { "godMode", "The player is immortal" },
                        { "hideHints", "Hide all on-screen hints (except the one you're reading)" },
                        { "infSprint", "Gives player infinite stamina" },
                        { "jumpForce", "Adjusts jump force" },
                        { "liteItems", "Items become lightweight (minimal weight)" },
                        { "multiJumps", "Allows multiple jumps in the air" },
                        { "noclip", "Fly through walls" },
                        { "noclipSpeed", "Speed while noclip is active" },
                        { "oneShotKill", "Kill enemies with one hit" },
                        { "rgbPlayer", "Automatically cycles player color" },
                        { "rgbPlayerUpdateInterval", "Color update interval (ms)" },
                        { "showDeadHeadsWH", "Highlight dead player heads" },
                        { "showEnemiesWH", "Highlight enemies" },
                        { "showEnemyHealthWH", "Show enemy health" },
                        { "showEnemyNameWH", "Show enemy name" },
                        { "showExPointsWH", "Highlight collection points" },
                        { "showItemNameWH", "Show item name" },
                        { "showItemPriceWH", "Show item price" },
                        { "showItemsWH", "Highlight valuables" },
                        { "showMoneyBagsWH", "Highlight money bags" },
                        { "showPlayerGlowWH", "Enable player glow" },
                        { "showPlayerHealthWH", "Show player health" },
                        { "showPlayerNameWH", "Show player name" },
                        { "showPlayersWH", "Highlight players" },
                        { "sortByPriceWH", "Sort valuables by price range" },
                        { "speedHack", "Adjusts player movement speed" },
                        { "sprintSpeedHack", "Sprint speed" },
                        { "valuablesDisableTouch", "Unfreeze on touch (when kinematic)" },
                        { "valuablesFreeze", "Keep kinematic after teleport" },
                        { "valuablesKinematic", "Freeze rigidbodies (kinematic) during teleport" },
                        { "valuablesOneAny", "Teleport one random item" },
                        { "valuablesTp", "Teleport valuables to player, collection point, or cart" },
                        { "valuablesTpOnTouch", "Teleport item on touch" },
                        { "walkSpeedHack", "Walk speed" },
                    }
                },
                {
                    1, new Dictionary<string, string>() // Russian
                    {
                        { "hintsColor", "Меняет цвет у статичных подсказок" },
                        { "MenuOpacity", "Изменяет прозрачность меню" },
                        { "PressLabelInfo", "Нажмите:" },
                        { "insertInfo", "открыть или закрыть меню." },
                        { "hideAllHints", "Скрывает все статичные подсказки" },
                        { "hideAllTooltips", "Скрывает все всплывающие подсказки" },
                        { "crouchSpeedHack", "Скорость при приседе" },
                        { "customfov", "Меняет угол обзора" },
                        { "dragWindow", "Разрешить перетаскивание окна меню" },
                        { "enemiesFreeze", "Сохранять заморозку после телепорта" },
                        { "enemiesKinematic", "Заморозить врага (kinematic) на время телепорта" },
                        { "enemiesOneAny", "Телепортировать одного случайного врага" },
                        { "enemiesTp", "Телепортирует врагов к игроку, на точки сбора или в пустоту" },
                        { "enemiesTpOnTouch", "Телепортировать врага при касании от игрока" },
                        { "flashlightSettings", "Управление параметрами фонарика" },
                        { "fragilityOff", "Отключает хрупкость предметов" },
                        { "fullbright", "Максимальная яркость по всей карте <color=yellow>(Багуется! Иногда нужно присесть для отключения.)</color>" },
                        { "ghostItems", "Режим призрачных предметов (проходят сквозь стены)" },
                        { "godMode", "Делает игрока бессмертным" },
                        { "hideHints", "Скрыть все подсказки на экране (кроме тех что вы читаете)" },
                        { "infSprint", "Даёт игроку бесконечную выносливость" },
                        { "jumpForce", "Управление силой прыжка" },
                        { "liteItems", "Режим лёгких предметов (минимальный вес)" },
                        { "multiJumps", "Позволяет прыгать несколько раз в воздухе" },
                        { "noclip", "Позволяет проходить сквозь стены и объекты" },
                        { "noclipSpeed", "Скорость перемещения в режиме noclip" },
                        { "oneShotKill", "Уничтожает врагов одним ударом/выстрелом" },
                        { "rgbPlayer", "Автоматическая смена цвета модели игрока" },
                        { "rgbPlayerUpdateInterval", "Частота обновления цвета (мс)" },
                        { "showDeadHeadsWH", "Подсвечивает головы мёртвых игроков" },
                        { "showEnemiesWH", "Подсвечивает врагов" },
                        { "showEnemyHealthWH", "Показывает здоровье врага" },
                        { "showEnemyNameWH", "Показывает имя врага" },
                        { "showExPointsWH", "Подсвечивает точки сбора" },
                        { "showItemNameWH", "Показывает название предмета" },
                        { "showItemPriceWH", "Показывает цену предмета" },
                        { "showItemsWH", "Подсвечивает ценные предметы" },
                        { "showMoneyBagsWH", "Подсвечивает мешки с деньгами" },
                        { "showPlayerGlowWH", "Включает подсветку игроков" },
                        { "showPlayerHealthWH", "Показывает здоровье игрока" },
                        { "showPlayerNameWH", "Показывает имя игрока" },
                        { "showPlayersWH", "Подсвечивает игроков" },
                        { "sortByPriceWH", "Сортировка предметов по цене (от и до)" },
                        { "speedHack", "Управление скоростью передвижения игрока" },
                        { "sprintSpeedHack", "Скорость бега" },
                        { "valuablesDisableTouch", "Снимать kinematic при касании" },
                        { "valuablesFreeze", "Сохранять kinematic после телепорта" },
                        { "valuablesKinematic", "Заморозить физику (kinematic) при телепорте" },
                        { "valuablesOneAny", "Телепортировать один случайный предмет" },
                        { "valuablesTp", "Телепортирует предметы к игроку, на точку сбора или в тележку" },
                        { "valuablesTpOnTouch", "Телепортировать предмет при касании" },
                        { "walkSpeedHack", "Скорость ходьбы" },
                    }
                },
                {
                    2, new Dictionary<string, string>() // Ukrainian
                    {
                        { "hintsColor", "Змінює колір статичних підказок" },
                        { "MenuOpacity", "Змінює прозорість меню" },
                        { "PressLabelInfo", "Натисніть:" },
                        { "insertInfo", "Відкрити або закрити меню." },
                        { "hideAllHints", "Приховує всі статичні підказки" },
                        { "hideAllTooltips", "Приховує всі спливаючі підказки" },
                        { "crouchSpeedHack", "Швидкість у присіді" },
                        { "customfov", "Змінює кут огляду" },
                        { "dragWindow", "Дозволити перетягування вікна меню" },
                        { "enemiesFreeze", "Зберігати заморозку після телепорту" },
                        { "enemiesKinematic", "Заморозити ворога (kinematic) під час телепорту" },
                        { "enemiesOneAny", "Телепортувати одного випадкового ворога" },
                        { "enemiesTp", "Телепортує ворогів до гравця, на точки збору або в порожнечу" },
                        { "enemiesTpOnTouch", "Телепортувати ворога при дотику від гравця" },
                        { "flashlightSettings", "Налаштування параметрів ліхтарика" },
                        { "fragilityOff", "Вимикає крихкість предметів" },
                        { "fullbright", "Максимальна яскравість на всій мапі" },
                        { "ghostItems", "«Примарні» предмети (проходять крізь стіни)" },
                        { "godMode", "Робить гравця безсмертним" },
                        { "hideHints", "Приховати всі підказки на екрані (крім тієї, що ви читаєте)" },
                        { "infSprint", "Надає гравцеві нескінченну витривалість" },
                        { "jumpForce", "Керування силою стрибка" },
                        { "liteItems", "Режим легких предметів (мінімальна вага)" },
                        { "multiJumps", "Дозволяє стрибати кілька разів у повітрі" },
                        { "noclip", "Дозволяє проходити крізь стіни та об'єкти" },
                        { "noclipSpeed", "Швидкість у режимі noclip" },
                        { "oneShotKill", "Знищує ворогів одним ударом/пострілом" },
                        { "rgbPlayer", "Автоматична зміна кольору моделі гравця" },
                        { "rgbPlayerUpdateInterval", "Інтервал оновлення кольору (мс)" },
                        { "showDeadHeadsWH", "Підсвічує голови мертвих гравців" },
                        { "showEnemiesWH", "Підсвічує ворогів" },
                        { "showEnemyHealthWH", "Показує здоров'я ворога" },
                        { "showEnemyNameWH", "Показує ім'я ворога" },
                        { "showExPointsWH", "Підсвічує точки збору" },
                        { "showItemNameWH", "Показує назву предмета" },
                        { "showItemPriceWH", "Показує ціну предмета" },
                        { "showItemsWH", "Підсвічує цінні предмети" },
                        { "showMoneyBagsWH", "Підсвічує мішки з грошима" },
                        { "showPlayerGlowWH", "Увімкнути підсвітку гравців" },
                        { "showPlayerHealthWH", "Показує здоров'я гравця" },
                        { "showPlayerNameWH", "Показує ім'я гравця" },
                        { "showPlayersWH", "Підсвічує гравців" },
                        { "sortByPriceWH", "Сортування предметів за ціною (від і до)" },
                        { "speedHack", "Керування швидкістю пересування гравця" },
                        { "sprintSpeedHack", "Швидкість бігу" },
                        { "valuablesDisableTouch", "Знімати kinematic при дотику" },
                        { "valuablesFreeze", "Зберігати kinematic після телепорту" },
                        { "valuablesKinematic", "Заморозити фізику (kinematic) під час телепорту" },
                        { "valuablesOneAny", "Телепортувати один випадковий предмет" },
                        { "valuablesTp", "Телепортує предмети до гравця, на точку збору або у візок" },
                        { "valuablesTpOnTouch", "Телепортувати предмет при захопленні" },
                        { "walkSpeedHack", "Швидкість ходи" },
                    }
                },
                {
                    3, new Dictionary<string, string>() // Chinese (简体中文)
                    {
                        { "hintsColor", "更改静态提示的颜色" },
                        { "MenuOpacity", "调整菜单透明度" },
                        { "PressLabelInfo", "按下:" },
                        { "insertInfo", "打开或关闭菜单。" },
                        { "hideAllHints", "隐藏所有静态提示" },
                        { "hideAllTooltips", "隐藏所有浮动提示" }, 
                        { "crouchSpeedHack", "蹲走速度" },
                        { "customfov", "更改视野范围 (FOV)" },
                        { "dragWindow", "允许拖动菜单窗口" },
                        { "enemiesFreeze", "传送后保持冻结" },
                        { "enemiesKinematic", "传送期间将敌人刚体设为 kinematic" },
                        { "enemiesOneAny", "传送一个随机敌人" },
                        { "enemiesTp", "将敌人传送到玩家、收集点或虚空" },
                        { "enemiesTpOnTouch", "接触/抓取时传送敌人" },
                        { "flashlightSettings", "自定义手电筒参数" },
                        { "fragilityOff", "禁用物品脆弱度" },
                        { "fullbright", "全地图强制最大亮度" },
                        { "ghostItems", "物品可穿墙" },
                        { "godMode", "使玩家无敌" },
                        { "hideHints", "隐藏所有屏幕提示（除当前阅读的提示）" },
                        { "infSprint", "给予玩家无限体力" },
                        { "jumpForce", "调整跳跃力度" },
                        { "liteItems", "物品轻量化（最小重量）" },
                        { "multiJumps", "允许空中多段跳" },
                        { "noclip", "穿墙模式" },
                        { "noclipSpeed", "穿墙模式速度" },
                        { "oneShotKill", "一击必杀" },
                        { "rgbPlayer", "自动循环玩家颜色" },
                        { "rgbPlayerUpdateInterval", "颜色更新间隔（毫秒）" },
                        { "showDeadHeadsWH", "高亮显示死亡玩家的头颅" },
                        { "showEnemiesWH", "高亮显示敌人" },
                        { "showEnemyHealthWH", "显示敌人生命值" },
                        { "showEnemyNameWH", "显示敌人名称" },
                        { "showExPointsWH", "高亮显示收集点" },
                        { "showItemNameWH", "显示物品名称" },
                        { "showItemPriceWH", "显示物品价格" },
                        { "showItemsWH", "高亮显示贵重物品" },
                        { "showMoneyBagsWH", "高亮显示钱袋" },
                        { "showPlayerGlowWH", "为玩家启用描边/发光" },
                        { "showPlayerHealthWH", "显示玩家生命值" },
                        { "showPlayerNameWH", "显示玩家名称" },
                        { "showPlayersWH", "高亮显示玩家" },
                        { "sortByPriceWH", "按价格区间排序物品" },
                        { "speedHack", "调整玩家移动速度" },
                        { "sprintSpeedHack", "冲刺速度" },
                        { "valuablesDisableTouch", "接触时取消 kinematic" },
                        { "valuablesFreeze", "传送后保持 kinematic" },
                        { "valuablesKinematic", "传送期间将刚体设为运动学 (kinematic)" },
                        { "valuablesOneAny", "传送一个随机物品" },
                        { "valuablesTp", "将物品传送到玩家、收集点或小车" },
                        { "valuablesTpOnTouch", "抓取时传送物品" },
                        { "walkSpeedHack", "行走速度" },
                    }
                },
            };

        public static string Get(string key)
        {
            if (packs.TryGetValue(Core.lg_state, out var dict))
            {
                if (dict.TryGetValue(key, out var value))
                    return value;
            }
            return null;
        }
    }
}
